#!/usr/bin/python
import socket
import os,sys
import uuid

def main():
	port=1584
	host = socket.gethostname()
	client_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
	try:
	    client_socket.connect((host, port))
	except:
	    print "No available server"
	    client_socket.close()
	    exit(0)
	val_mc = hex(uuid.getnode()).replace('0x','').upper()
	mac_ad = ':'.join(val_mc[i : i + 2] for i in range(0, 11, 2))	
	if len(sys.argv)==1:
		client_socket.send(str(mac_ad))
	elif sys.argv[1]=="-m" and len(sys.argv)==3:
		try:
			client_socket.send(str(sys.argv))
		except:
			print "Error in Connection"
			exit(0)
	else:
		print "Invalid Arguments Given"
		exit(0)

	ntw_info=[]
	while True:
		data=client_socket.recv(4096)
		if data=="done":
			break
		client_socket.send("received")
		ntw_info.append(data)
	for i in ntw_info:
		print i


if __name__=="__main__":
	main()